M48
; DRILL file {KiCad 9.0.4} date 2025-10-04T23:29:17+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-10-04T23:29:17+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.500
%
G90
G05
T1
X77.11Y-175.0
X82.89Y-175.0
T2
X63.0Y-113.5
X63.0Y-177.0
X97.0Y-113.5
X97.0Y-177.0
M30
